export const datas = [
  {
    "ten_cay": "Cây Me Tây",
    "slug": "cay-me-tay",
    "id_danh_muc": 12,
    "id_phan_loai": 0,
    "id_chung_loai": 0,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_me_tay.jpg",
    "ten_pho_thong": "Cây Me Tây",
    "ten_khoa_hoc": "Tamarindus indica",
    "ho_thuc_vat": "Fabaceae (Đậu)",
    "nguon_goc_xuat_su": "Châu Mỹ Nhiệt đới",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Là cây thân gỗ, có thể cao đến 20m, lá kép lông chim chẵn, gồm 10-12 cặp lá chét có gốc không cân xứng, chóp lõm. \nHoa, Qủa, Hạt: Chùm hoa ở ngọn các nhánh nhỏ, có 8-12 hoa. Hoa có 2 lá bắc vàng, dính nhau thành chóp và rụng sớm; 4 lá đài trắng; 3 cánh hoa vàng có gân đỏ. Quả dài, mọc thõng xuống, hơi dẹt, thẳng, thường chứa 3-5 hạt màu nâu sẫm, trơn. Nạc hay thịt của quả (cơm quả) chua. Mùa quả tháng 10-11.",
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": "Cây ưa sáng, thích hợp với nhiều loại đất. Có khả năng chịu được các điều kiện bất lợi của môi trường: Hạn, thiếu dinh dưỡng… vì có hệ rễ phát triển rộng và sâu.",
    "chi_tiet_khac": "0",
    "ghi_chu": null,
    "mo_ta": null,
    "id": 9,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:48.59",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": "2019-07-10T16:35:24.387",
    "nguoi_cap_nhat": "administrator"
  },
  {
    "ten_cay": "Cây Móng Bò Tím",
    "slug": "cay-mong-bo-tim-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_mong_bo.jpg",
    "ten_pho_thong": "Cây Móng Bò Tím",
    "ten_khoa_hoc": "Bauhinia purpurea",
    "ho_thuc_vat": "Caesalpiniaceae (Vang)",
    "nguon_goc_xuat_su": "Trung Quốc, Ấn Độ, Mianma",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, tán, lá: Cây gỗ nhỏ trung bình, cao 2-6, phân cành dài, tán rộng, thưa. Lá to, hình tim ở gốc, đầu có 2 thùy thuôn dạng tròn, màu xanh bóng, nhẵn, gốc có 9-11 gân rõ.\nHoa, Qủa, Hạt: Cụm hoa dạng chùm thưa, mang hoa lớn, màu đỏ tím, rất đẹp, ở ngọn cành hay nách các lá ở đỉnh, có hương thơm. Hoa có cánh tràng mềm, mép răn reo kéo dài và hẹp thành móng ở gốc, ở giữa có một cánh thìa dạng thuôn hình giáo nổi rõ đốm trắng. Qủa lớn, dẹt thuôn đều, dài 30cm, hạt dẹt.",
    "toc_do_sinh_truong": "Nhanh",
    "phu_hop_voi": "Cây ưa sáng, đất giàu dinh dưỡng, thoát nước tốt, không cần cắt tỉa thường xuyên, sức sống có thể giảm sau thời kỳ ra hoa cần được chăm sóc và bổ sung chất dinh dưỡng.\nCây trồng bằng hạt, ươm gieo ở vườn ươm trong bầu, sau 1 năm đem trồng nơi cố định. Cần có đất tốt, đủ nước và đủ nắng. Cây ít đòi hỏi chăm sóc.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 10,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:48.657",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Muồng Hoa Đào",
    "slug": "cay-muong-hoa-dao-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_muong_hoa_dao.jpg",
    "ten_pho_thong": "Cây Muồng Hoa Đào",
    "ten_khoa_hoc": "Cassia javanica Linn",
    "ho_thuc_vat": "Caesalpiniaceae",
    "nguon_goc_xuat_su": "Nam Á",
    "phan_bo_o_viet_nam": "Miền Nam",
    "dac_diem_hinh_thai": "Đặc điểm hình thái:\nThân, Tán, Lá: Cây gỗ trung bình, phân cành nhiều thấp.\nCành dài, xoè rộng tán thưa. Lá kép lông chim với 8 – 12 đôi lá phụ xếp cách nhau đều đặn, dạng thuôn dài, màu xanh nhạt, mốc.\nHoa, Quả, Hạt: Cụm hoa dạng chuỳ lớn, kép, thẳng đứng mang nhiều hoa màu hồng. Hoa có cánh tràng gần bằng nhau, mảnh, dễ rụng. Quả hình trụ dài 30 - 40cm, màu đen bóng. Hạt dẹt",
    "toc_do_sinh_truong": "Nhanh",
    "phu_hop_voi": "Cây dễ trồng thích nghi với nhiều điều kiện sống khác nhau. Tuy nhiên phát triển tốt nhất khi đất tơi xốp, thoát nước và chiếu sang hoàn toàn.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 11,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:48.71",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Ngọc Lan",
    "slug": "cay-ngoc-lan-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_ngoc_lan.jpg",
    "ten_pho_thong": "Cây Ngọc Lan",
    "ten_khoa_hoc": "Michelia alba",
    "ho_thuc_vat": "Magnoliaceae (Ngọc lan)",
    "nguon_goc_xuat_su": "Ấn Độ",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Cây gỗ lớn, võ nhẵn mùa xám, phân cành nhánh dài thẳng. Lá thuôn bầu dục, đầu nhọn, gốc tù, mặt trên nhẵn, mặt dưới có lông thưa.  \nHoa, Qủa, Hạt: Hoa đơn độc ở nách lá thơm, có 10 - 15 cánh hình dải thuôn xếp xoắn ốc. Nhị nhiều, ngắn và hẹp, quả kép hình nón.\nĐặc điểm sinh lý, sinh thái:",
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": "Cây ưa sáng hoặc chịu bóng một phần. Đất nhiều mùn, thoát nước tốt, pH trung bình.\nNhân giống từ hạt hặc giâm cành. Cây khó bứng hoặc ghép cành.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 12,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:48.777",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Osaka Vàng",
    "slug": "cay-osaka-vang-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_osaka_vang.jpg",
    "ten_pho_thong": "Cây Osaka Vàng",
    "ten_khoa_hoc": "Cassia fistula",
    "ho_thuc_vat": "Caesalpiniaceae (Vang).",
    "nguon_goc_xuat_su": "Ấn Độ, Srilanca.",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Cây gỗ trung bình, cao 10 - 20m, thân tròn nhẵn, phân cành nhánh dài, mềm mọc thẳng, tán hẹp và thưa. Lá kép lông chim với 3 - 8 đôi lá phụ, dày màu xanh nhạt, hơi mốc ở mặt dưới.\nHoa, Qủa, Hạt:  Chùm hoa buông xuống mọc từ nách lá, dài 30 - 50cm mang nhiều hoa xếp thưa có cuống dài. Hoa lớn trung bình màu vàng chanh, cánh hoa mềm mở rộng và nở dần từ gốc lên ngọn. Quả lớn, dài 30 - 40cm. Hạt dẹt, mảnh. Mùa ra hoa: mùa nắng (khoảng tháng 3-7).",
    "toc_do_sinh_truong": "Nhanh",
    "phu_hop_voi": "Phù hợp với: Cây dễ trồng thích nghi với nhiều điều kiện sống khác nhau. Tuy nhiên phát triển tốt nhất khi đất tơi xốp, thoát nước và chiếu sáng hoàn toàn. Cây trồng bằng hạt hay các chồi rễ.\nCây cho hoa đẹp, hoa nhiều, trùm lên hết tán lá nên rất được ưa chuộng trồng làm cảnh ở các vườn hoa, công viên, và tô điểm cho các công trình kiến trúc khác.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 13,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:48.837",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Osaka Đỏ",
    "slug": "cay-osaka-do-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_osaka_do.jpg",
    "ten_pho_thong": "Cây Osaka Đỏ",
    "ten_khoa_hoc": "Erythrina fusca",
    "ho_thuc_vat": "Fabaceae (Đậu).",
    "nguon_goc_xuat_su": "Các nước nhiệt đới Châu Á.",
    "phan_bo_o_viet_nam": "miền nam",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Cây gỗ trung bình, cao 10-20m, có gai ngắn, vỏ non màu xanh sau chuyển sang màu .nâu dày, xốp. Cành nhỏ thẳng, khẳng khiu mang lá tập trung ở gần đỉnh. Lá có 3 lá phụ dạng bầu dục gần tròn hay hình tam giác lệch, lá phụ cuối cùng lớn hơn cả, màu lục bóng, nhẵn, rụng vào mùa mưa.\nHoa, Qủa, Hạt: Cụm hoa dạng chùm dày mang nhiều hoa màu đỏ sát nhau. Hoa lớn có 1 cánh cờ dạng trái xoan thuôn rộng, cuộn lại. Nhị hợp lại thành bó dài. Quả dài 25cm màu đen, nhẵn, thắt lại ở hạt. Hạt 5 - 8, hình thận, đỏ hay nâu.  Mùa ra hoa: ra hoa quanh năm",
    "toc_do_sinh_truong": "Nhanh",
    "phu_hop_voi": "Cây ưa sáng, đất có pH = 6-8, vùng thấp trũng, ven biển, đầm lầy, vùng đất ngập nước, ven sông. Nói chung nó thích nghi với các điều kiện vùng duyên hải, chịu được cả ngập lụt lẫn điều kiện đất mặn.Cây có nhu cầu nước cao",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 14,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:48.9",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Phượng Vỹ",
    "slug": "cay-phuong-vy-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_phuong_vy_do.jpg",
    "ten_pho_thong": "Cây Phượng Vỹ",
    "ten_khoa_hoc": "Delonix regia",
    "ho_thuc_vat": "Caesalpiniaceae (Vang)",
    "nguon_goc_xuat_su": "Madagascar",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, tán, lá: Cây gỗ lớn, cao 10 - 20m, tán hình nấm, vỏ thân màu xám trắng, nhẵn, phân cành nhánh nhiều, lớn, dài mọc nghiêng, nên tán mở rộng và dày. Lá kép lông chim 2 lần với 20 đôi lá phụ, rụng thưa vào mùa khô.\nHoa, Qủa, Hạt: Cụm hoa lớn, dài 20 - 50cm, mang hoa xếp thưa, xoè rộng. Hoa lớn, màu đỏ tươi với cánh tràng có cuống dài, phiến rộng răn reo, trong đó có cánh lớn màu cam đỏ và các các vạch đốm màu trắng. Nhị có bao phấn cong màu đỏ. Hoa nở rộ vàn tháng 4-7, làm cho tán cây được bao trùm bởi một màu đỏ. Quả rất lớn, dài 20 - 60cm, rộng 4 - 6cm, dẹt, vỏ hoá gỗ. Hạt rất cứng. Mùa ra hoa: từ tháng 4-6. Hoa đỏ rực. Trồng nhiều ở vỉa hè, công viên, trường học.",
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": "Cây ưa sáng, phù hợp với đất giàu dinh dưỡng, ẩm nhưng phải thoát nước tốt, thân dòn dễ gãy nên cần được bảo vệ trước gió lớn. Hệ rễ lớn có thể gây tổn hại tới đường và các công trình công cộng",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 15,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:48.963",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Sao Đen",
    "slug": "cay-sao-den-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_sao_den.jpg",
    "ten_pho_thong": "Cây Sao Đen",
    "ten_khoa_hoc": "Hopea odorata",
    "ho_thuc_vat": "ipterocarpaceae (Dầu)",
    "nguon_goc_xuat_su": "Ấn Độ, Bangladesh, Campuchia, Lào, Malaysia, Myanma, Thái Lan và Việt Nam.",
    "phan_bo_o_viet_nam": "Chủ yếu ở các tỉnh từ Quảng Nam trở vào và nhiều nhất ở các tỉnh Đông Nam Bộ và Nam Tây Nguyên và cho đến hiện nay thì loài cây này cũng đã được nhân gống ở một số tỉnh miền Bắc",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Là cây thân gỗ lớn, có thể cao đến 30-40m, đường kính thân: 70-80cm. Lá đơn hình trái xoan thuôn, mặt trên nhẵn, mặt dưới có lông. Thân hình trụ thẳng, tán nhỏ, vỏ màu nâu đen, cành non và cuống lá phủ lông.\nHoa, Qủa, Hạt: Hoa màu vàng nhạt. Quả nhỏ hình trứng 7-8cm, có 2 cánh. Mùa hoa tháng 2, ra quả tháng 3 và kết thúc vào tháng 5. Cây thường 2 năm ra quả 1 lần.",
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": "Ưa ẩm, ưa sáng, lúc nhỏ có thể chịu bóng",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 16,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.033",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Sứ Đại",
    "slug": "cay-su-dai-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": null,
    "ten_pho_thong": "Cây Sứ Đại",
    "ten_khoa_hoc": "Plumeria obtusa",
    "ho_thuc_vat": "Apocynaceae (Trúc đào)",
    "nguon_goc_xuat_su": "Châu Mỹ",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Cây gỗ trung bình, mập, khẳng khiu, phân cành nhánh dài, cong queo, xù xì. Vỏ màu trắng xám, xốp. Lá thuôn dài lớn, rộng ở giữa và hẹp lại ở cuống, đầu lá tù, màu xanh bóng, nhẵn, gân nổi rõ màu trắng kéo dài nổi với gân viền ở mép. Lá xếp sát nhau thành vòng ở ngọn cành, khi rụng để lại sẹo lớn ở cành. \nHoa, Qủa, Hạt: Cụm hoa trên một cuống chung, mập, dài 30 - 50cm, phân nhánh vòng ở đỉnh, có nhiều sẹo do hoa rụng. Hoa có cánh dày, mập, tiền khai hoa vặn, màu trắng tâm vàng đậm, lớn. Quả ít gặp, gồm 2 đại. Hạt có cánh.",
    "toc_do_sinh_truong": "Nhanh",
    "phu_hop_voi": "Cây ưa sáng, đất giàu dinh dưỡng, thoát nước tốt. Khả năng chịu khô hạn cao. Nhân giống từ giâm cành",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 17,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.103",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Sứ Trắng",
    "slug": "cay-su-trang-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": null,
    "ten_pho_thong": "Cây Sứ Trắng",
    "ten_khoa_hoc": "Plumeria alba",
    "ho_thuc_vat": "Apocynaceae (Trúc đào).",
    "nguon_goc_xuat_su": "Châu Mỹ",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Là cây thân gỗ trung bình, có thể cao đến 8-9m, lá thuôn hẹp dài, nhọn ở đỉnh, màu xanh bóng, mặt dưới có lông dày, xếp sát nhau ở đầu cành và thường rụng lá vào mùa khô. \nHoa, Qủa, Hạt: Hoa ở đầu cành trên cuống chung dài, hoa có cánh dày màu trắng, gốc họng màu vàng nghệ. Rất ít khi có quả.",
    "toc_do_sinh_truong": "Nhanh",
    "phu_hop_voi": "Cây ưa sáng, đất giàu dinh dưỡng, thoát nước tốt. Khả năng chịu khô hạn cao. Nhân giống từ giâm cành.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 18,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.18",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Liễu Rủ",
    "slug": "cay-lieu-ru-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_lieu_ru.jpg",
    "ten_pho_thong": "Cây Liễu Rủ",
    "ten_khoa_hoc": "Callistemon citrinus, Callistemon lanceolatus",
    "ho_thuc_vat": "Myrtaceae (Sim).",
    "nguon_goc_xuat_su": "Australia",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Cây gỗ nhỏ cao 2 - 4m, phân cành nhiều, dài rủ xuống như liễu. Lá hình giáo thuôn đều cả hai đầu, có 3 gân, lúc non có lông, màu đỏ nhạt. \nHoa, Qủa, Hạt: Cụm hoa bông dài, xếp sát nhau dày đặc với chỉ nhị màu đỏ, nổi trên cánh hoa. Quả nang hình chuông, nhỏ",
    "toc_do_sinh_truong": "Nhanh",
    "phu_hop_voi": "Cây ưa sáng, đất ẩm ướt nhưng thoát nước tốt",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 19,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.247",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Bồ Đề",
    "slug": "cay-bo-de-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_bo_do.jpg",
    "ten_pho_thong": "Cây Bồ Đề",
    "ten_khoa_hoc": "Ficus religiosa",
    "ho_thuc_vat": "Moraceae (Dâu tằm).",
    "nguon_goc_xuat_su": "Ấn Độ",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Cây thân gỗ lớn, có thể hãm thành cây uốn thế, vỏ màu xám, phân cành nhánh nhiều cong rủ xuống. Lá dạng trái tim, cuống dài, kéo dài thành dải 2-5cm ở đỉnh, gốc tim, màu xanh lục đậm nổi bật gân lông chim. \nHoa, Qủa, Hạt: Cụm hoa dạng sung trên thân, dạng cầu, khi chín màu tím đậm.",
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": "Cây ưa sáng hoặc chịu bóng bán phần. Đất giàu mùn, dinh dưỡng, ẩm và thoát nước tốt. Nhân giống dễ dàng từ hạt và giâm cành, dễ uốn tỉa",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 20,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.307",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Dừa Ta",
    "slug": "cay-dua-ta-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_dua_ta.jpg",
    "ten_pho_thong": "Cây Dừa Ta",
    "ten_khoa_hoc": "Cocos nucifera",
    "ho_thuc_vat": "Arecaceae (Cau)",
    "nguon_goc_xuat_su": "Châu Mỹ Nhiệt đới",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Cây thân cột, cao, đường kính thân 50cm, có thể cao tới 20m. Thân có sẹo do lá rụng để lại. Gốc thân hơi phình rộng, mang nhiều rễ nổi. Lá mọc tập trung ở đầu cành, kép lông chim, dài 2-4m, cuống lớn cong, gốc có bẹ lớn lôm thân, lá phụ dạng dải, màu xanh bóng, có 1 gân chính lớn, cứng.\nHoa, Qủa, Hạt: Cụm hoa đơn tính cùng gốc. Hoa đực màu vàng nhỏ, hoa cái lớn. Quả lớn, có nước ngọt, mát.",
    "toc_do_sinh_truong": "Chậm",
    "phu_hop_voi": "Cây ưa sáng, giai đoạn còn nhỏ đòi hỏi phải che bóng, đất thoát nước tốt, trồng cổ rễ cao hơn miệng hố. Nhân giống từ hạt hoặc tách các bụi nhỏ.  Nhu cầu nước trung bình. Cho hoa và quả quanh năm.\nDừa là cây cho giá trị kinh tế cao vừa để làm cây kiểng, toàn bộ thân lá rể thân dừa được tậng dụng làm nhiều sản phẩm đẹp và làm thủ công mỹ nghệ. Ngoài những công dụng trên hiện nay cây dừa đã được phổ biến  trồng trong chậu làm cây kiểng hoặc trồng xuống đất làm làm bóng mát  trong các công viên, nhà hàng khách sạn, sân vườn biệt thự, các khu du lich, resort, trồng ven hồ bờ nước tạo dáng đẹp mắt. Chúng chịu đựng được với mọi gió lớn nên có thể trồng trên sân thượng và và trồng kè đễ giữ đất xung quanh bờ sông rạch, Dễ chăm sóc.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 21,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.37",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Đa Búp Đỏ",
    "slug": "cay-da-bup-do-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_da_bup_do.jpg",
    "ten_pho_thong": "Cây Đa Búp Đỏ",
    "ten_khoa_hoc": "Ficus elastica",
    "ho_thuc_vat": "Moraceae (Dâu tằm)",
    "nguon_goc_xuat_su": "Vùng nhiệt đới Châu Á",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, tán, lá: Cây gỗ lớn cao đến 30m, hệ rễ khỏe. Lá đơn mập, mọc cách, mép nguyên, lá non có màu đỏ pha xanh, búp bao chồi dạng lớn màu đỏ.\nHoa, Qủa, Hạt: Cụm hoa dạng sung màu cam sau chuyển sang màu đen",
    "toc_do_sinh_truong": "Nhanh",
    "phu_hop_voi": "Cây ưa sáng hoặc chịu bóng bán phần. Đất giàu mùn, dinh dưỡng ẩm và thoát nước tốt. Nhân giỗng dễ dàng từ hạt và giâm cành.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 22,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.437",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Đa Lâm Vồ",
    "slug": "cay-da-lam-vo-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_da_lam_vo.jpg",
    "ten_pho_thong": "Cây Đa Lâm Vồ",
    "ten_khoa_hoc": "Ficus rumphii",
    "ho_thuc_vat": "Moraceae (Dâu tằm)",
    "nguon_goc_xuat_su": "Ấn Độ, Malaisia",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Cây gỗ lớn, có nhánh to, vỏ nhẵn, môc trắng. Lá hình tam giác cụt, có khi hơi thót lại ở cuống, cso mũi nhọn hình tam giác, màu lục nhạt ở cả 2 mặt, dài 8-12 cm, cuống lá mảnh.\nHoa, Qủa, Hạt: Qủa sung xếp từng cặp trên nhánh có lá, không có cuống, hình cầu, khi chín màu đỏ sẫm.",
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": "Cây ưa sáng, đất giàu dinh dưỡng, thoát nước tốt",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 23,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.5",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Đào Tiên",
    "slug": "cay-dao-tien-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_dao_tien.jpg",
    "ten_pho_thong": "Cây Đào Tiên",
    "ten_khoa_hoc": "Crescentia cujete Linn.",
    "ho_thuc_vat": "Bignoniaceae",
    "nguon_goc_xuat_su": "Châu Mỹ nhiệt đới",
    "phan_bo_o_viet_nam": "Miền Nam",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Cây gỗ nhỏ, nhẵn, lá mọc chụm đầu cành, dạng thuôn hình giáo, gốc kéo dài ở cuống, đầu lá rộng, màu xanh đậm, bóng, cứng, tán dày.\nHoa, Quả, Hạt: Hoa mọc đơn độc ở đầu cành hay kẽ lá, buông thõng xuống, với cánh tràng màu vàng xanh, gốc màu đỏ tía, điểm các hạt nhỏ, hợp thành ống loe ở đỉnh trên chia 2 môi. Quả lớn hình cầu, vỏ cứng, nhiều hạt.",
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": "Cây ưa sáng, nhu cầu nước trung bình.\n Nhân giống từ hạt.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 24,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.56",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Đầu Lân",
    "slug": "cay-dau-lan",
    "id_danh_muc": 0,
    "id_phan_loai": 0,
    "id_chung_loai": 0,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_dau_lan.jpg",
    "ten_pho_thong": "Cây Đầu Lân",
    "ten_khoa_hoc": "Couroupita guianensis, Couroupita surinamensis",
    "ho_thuc_vat": "Lecythidaceae (Lộc vừng)",
    "nguon_goc_xuat_su": "Châu Mỹ nhiệt đới",
    "phan_bo_o_viet_nam": "Miền Nam",
    "dac_diem_hinh_thai": null,
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": null,
    "chi_tiet_khac": "0",
    "ghi_chu": null,
    "mo_ta": "asdawdasda",
    "id": 25,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.623",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": "2019-06-12T14:01:56.293",
    "nguoi_cap_nhat": "administrator"
  },
  {
    "ten_cay": "Cây Hoàng Nam",
    "slug": "cay-hoang-nam-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_hoang_nam.jpg",
    "ten_pho_thong": "Cây Hoàng Nam",
    "ten_khoa_hoc": "Polyalthia longifolia",
    "ho_thuc_vat": "Annonaceae (Na)",
    "nguon_goc_xuat_su": "Sri Lanka, Bắc Ấn Độ",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Thân gỗ, thẳng cao, tán hẹp dạng tháp. Lá thuôn dài, mềm, cong xuống, dày đặc, che kín hết cành thân, lá xanh quanh năm.\nHoa, Qủa, Hạt: Hoa màu xanh xám, cánh răn reo thơm. Quả dạng bầu dục, màu đen.",
    "toc_do_sinh_truong": "Nhanh",
    "phu_hop_voi": "Cây ưa khí hậu ẩm, đất tơi xốp, thoát nước tốt và cần che bóng tốt khi còn nhỏ. Cây có khả năng thích nghi và sức sống cao",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 26,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.683",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Kiều Hùng",
    "slug": "cay-kieu-hung-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_kieu_hung.jpg",
    "ten_pho_thong": "Cây Kiều Hùng",
    "ten_khoa_hoc": "Calliandra hematocephala",
    "ho_thuc_vat": "Mimosaceae",
    "nguon_goc_xuat_su": "Châu Mỹ",
    "phan_bo_o_viet_nam": "Miền Nam",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Cây gỗ nhỏ dạng bụi, cành dài mềm, loà xoà sát đất. Lá kép lông chim có 2 - 4 đôi lá phụ dạng thuôn lệch, màu xanh, bóng,nhẵn.\nHoa, Quả, Hạt: Hoa nhỏ, màu đỏ tươi, cả cánh hoa ở gốc lẫn nhị đực thò ra thẳng. Quả ít gặp.",
    "toc_do_sinh_truong": "Chậm",
    "phu_hop_voi": "Cây ưa sáng, phát triển tốt trong điều kiện thoát nước tốt, đầy đủ dinh dưỡng. Chế độ nước rất cần thiết trong giai đoạn sinh trưởng.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 27,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.747",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Long Não",
    "slug": "cay-long-nao-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_long_nao.jpg",
    "ten_pho_thong": "Cây Long Não",
    "ten_khoa_hoc": "Cinnamomum camphora",
    "ho_thuc_vat": "Lauraceae (Long não)",
    "nguon_goc_xuat_su": "Đông Á, Đài Loan, miền Nam Nhật Bản, Đông Nam Trung Quốc",
    "phan_bo_o_viet_nam": "",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Là một loại cây thân gỗ, lớn và thường xanh, có thể cao tới 20-30 m. Vỏ thân dày nứt nẻ. Tán lá rộng. Lá mọc so le có cuống dài, ở kẽ gân chính và gân 2 bên nổi lên 2 tuyến nhỏ. Các lá nhẵn và bóng, bề mặt như sáp và có mùi long não khi bị vò nát trong tay.\nHoa, Qủa, Hạt: Hoa nhỏ màu vàng lục mọc thành chùm ở kẽ lá. Mùa hoa từ tháng 3-4. Quả mọng khi chín có màu đen. Quả chín tháng 10-11.",
    "toc_do_sinh_truong": "Chậm",
    "phu_hop_voi": "Cây ưa sáng, ưa ẩm",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 28,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.807",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Muồng Hoa Vàng",
    "slug": "cay-muong-hoa-vang-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_muong_hoa_vang.jpg",
    "ten_pho_thong": "Cây Muồng Hoa Vàng",
    "ten_khoa_hoc": "Cassia splendida",
    "ho_thuc_vat": "Caesalpiniaceae (Vang)",
    "nguon_goc_xuat_su": "Nam Mỹ",
    "phan_bo_o_viet_nam": "Miền Nam",
    "dac_diem_hinh_thai": "Thân, tán, lá: Cây gỗ nhỏ, phân cành nhánh thấp, tán xoè rộng. Lá kép lông chim với 8 - 12 đôi lá phụ màu xanh bóng, mềm mại.\nHoa, Qủa, Hạt: Cụm hoa dạng chuỳ, mang hoa xếp thưa. Hoa lớn có cánh tràng lớn tròn mở rộng, màu vàng sáng. Hoa nở bền, mùa hoa kéo dài gần quanh năm. Quả đậu dẹt, thẳng.",
    "toc_do_sinh_truong": "Nhanh",
    "phu_hop_voi": "Cây dễ trồng thích nghi với nhiều điều kiện sống khác nhau, chịu được khô hạn, không chịu ngập úng, phát triển tốt trên đất tơi xốp và thoát nước. Tuy nhiên phát triển tốt nhất khi đất tơi xốp, thoát nước và chiếu sáng hoàn toàn.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 29,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.87",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Sake",
    "slug": "cay-sake",
    "id_danh_muc": 0,
    "id_phan_loai": 0,
    "id_chung_loai": 0,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_sake.jpg",
    "ten_pho_thong": "Cây Sake",
    "ten_khoa_hoc": "Artocarpus altilis",
    "ho_thuc_vat": "Moraceae (Dâu tằm)",
    "nguon_goc_xuat_su": "Các nước Châu Á nhiệt đới",
    "phan_bo_o_viet_nam": "Miền Nam",
    "dac_diem_hinh_thai": null,
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": null,
    "chi_tiet_khac": "0",
    "ghi_chu": null,
    "mo_ta": "#=mo_ta !=null ? mo_ta: ''#",
    "id": 30,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:49.937",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": "2019-06-12T14:00:01.87",
    "nguoi_cap_nhat": "administrator"
  },
  {
    "ten_cay": "Cây Bàng Vuông",
    "slug": "cay-bang-vuong-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_bang_vuong.jpg",
    "ten_pho_thong": "Cây Bàng Vuông",
    "ten_khoa_hoc": "Bucida molineti hoặc Terminalia molineti",
    "ho_thuc_vat": "Combretaceae (Bàng)",
    "nguon_goc_xuat_su": "Bahamas.",
    "phan_bo_o_viet_nam": "Miền Nam",
    "dac_diem_hinh_thai": "Thân, Tán, Lá: Cây gỗ nhỡ, phân cành nhánh nhiều gần như mọc vòng, nằm ngang làm cho tán cây có nhiều tầng, vỏ màu nâu xám. Lá mọc tập trung đầu cành, dạng trái xoan ngược, đầu gần tròn, gốc thuôn dài.\nHoa, Qủa, Hạt: Hiếm thấy hoa.",
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": "Cây ưa sáng, đất giàu dinh dưỡng, thoát nước tốt, không cần cắt tỉa thường xuyên, sức sống có thể giảm sau thời kỳ ra hoa cần được chăm sóc và bổ sung chất dinh dưỡng.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 31,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:50.007",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Cà Na",
    "slug": "cay-ca-na-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_ca_na.jpg",
    "ten_pho_thong": "Cây Cà Na",
    "ten_khoa_hoc": "Elaeocarpus hygrophilus Kurz",
    "ho_thuc_vat": "Côm (Elaeocarpaceae)",
    "nguon_goc_xuat_su": "Madagascar ở phía tây qua Ấn Độ, Đông Nam Á, Malaysia, nam  Trung Hoa, và Nhật Bản, qua Australia đến New Zealand, Fiji, và Hawaii ở phía đông. Các đảo Borneo và New Guinea",
    "phan_bo_o_viet_nam": "Tây Nam Bộ",
    "dac_diem_hinh_thai": "Cà na là cây đại mộc sống lâu năm, sống được trên vùng đất ẩm hoặc có dao động thủy triều.\nThân: Cà na là cây thân gỗ cao từ 10-25m, có thể đến 30 m.\nRể: Rể phát triển mạnh, lan tỏa rộng trong đất bùn, ở gốc thân có nhiều rể khí sinh mọc thành chùm.\nLá: Lá có phiến hình trái xoan ngược, thót lại trên cuống về phía gốc, thoát tù lại ở đầu, rất nhẵn, dai, màu lục ở mặt trên, nhạt ở mặt dưới, có răng lượn sóng, dài 4-9 cm, rộng 1, 8-3 cm.\nHoa: Hoa mọc thành chùm có lông mềm, màu bạc ở nách những lá đã rụng, dài 4-7 cm, có cuống dài 3-5mm.\nQuả: Quả hạch hình bầu dục nhọn, dài 3 cm. Quả già có màu xanh đậm, vị chát; còn trái chín có màu xanh nhạt, vị chua.\nHạt: Hạt hình thoi, có vỏ hạt cứng, mỗi quả có 1 hạt.",
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": "Cà na là loài cây hoang dại mọc trên vùng đất phèn, mặn.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 32,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:50.073",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Cẩm Lai",
    "slug": "cay-cam-lai-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_cam_lai.jpg",
    "ten_pho_thong": "Cây Cẩm Lai",
    "ten_khoa_hoc": "Dalbergia bariaensis Pierre",
    "ho_thuc_vat": "Họ Đậu – Fabaceae",
    "nguon_goc_xuat_su": "khu vực nhiệt đới của Trung và Nam Mỹ, châu Phi, Madagascar và Nam Á.",
    "phan_bo_o_viet_nam": "Tây Nguyên, Đồng Nai",
    "dac_diem_hinh_thai": "Thân, tán , lá: Cây thân gỗ, có đặc điểm không nứt, chiều cao từ 20-25m, đường kính khoảng 40-60cm, vỏ màu xám tro. Tán cây xòe rộng, hình dù. Lá kép lông chim một lần, dài 15-18cm.\nHoa, quả, hạt: Cụm hoa chùy ở nách lá và đầu cành, hoa nhỏ, màu lam nhạt. Quả đậu dẹt, hơi thắt eo ở chỗ có hạt. Hạt 1(ít khi 2), hình thận, dẹt, màu đen nhạt.",
    "toc_do_sinh_truong": "Chậm",
    "phu_hop_voi": "Nơi ẩm ven sông suối nơi đất tương đối bằng. Cây ưa đất feralit nâu đỏ hay nâu vàng phát triển trên đá bazan, feralit xám trên cát kết hay phù sa cổ có tầng dày, thoát nước. Cây ưa sáng, lúc nhỏ chịu nóng.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 33,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:50.14",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Gáo Trắng",
    "slug": "cay-gao-trang-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_gao_trang.jpg",
    "ten_pho_thong": "Cây Gáo Trắng",
    "ten_khoa_hoc": "Neolamarckia cadamba",
    "ho_thuc_vat": "Rubiaceae",
    "nguon_goc_xuat_su": "Nam Trung Hoa, Nam Á, Đông Nam Á tới vùng đảo Papua.",
    "phan_bo_o_viet_nam": "",
    "dac_diem_hinh_thai": "Là cây gỗ thường xanh quanh năm thuộc họ Thiến thảo (Rubiaceae). Cây thuộc nhóm gỗ lớn, trong tự nhiên có thể dễ dàng tìm thấy cây cao tới 30–45 m, thuộc tầng cây vượt tán rừng. Thân cây thuộc nhóm thân đơn trục, có các cành nhánh đâm ngang. Vỏ thân cây màu xám, gỗ giác màu trắng, gỗ lõi màu cam nhạt. Lá cây có phiến hình bầu dục dài 13–32 cm (5,1–12,6 in), đầu lá có mũi nhọn, đuôi lá có thể tròn hoặc tà. Mặt dưới lá có lớp lông mịn. Lá kèm sớm rụng, dạng lá kèm thon nhọn dài 1,5–2 cm. Thường bắt đầu ra hoa khi 3-4 năm tuổi. Hoa mọc ở đầu cành nhánh, có mùi thơm, màu từ đỏ tới cam. Quả dạng phức kép hình cầu đường kính 2-4,5 cm.",
    "toc_do_sinh_truong": "Chậm",
    "phu_hop_voi": "Có thể trồng ở vùng ven bán ngập của các hồ thủy điện, tăng sinh khối gỗ cho mô hình trồng rừng kết hợp tre - gỗ. Tuy nhiên hạn chế dùng cây làm cây xanh đô thị do sinh trưởng loài nhanh, gỗ mềm dễ gãy đổ.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 34,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:50.203",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Gõ Đỏ",
    "slug": "cay-go-do-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_go_do.jpg",
    "ten_pho_thong": "Cây Gõ Đỏ",
    "ten_khoa_hoc": "Afzelia xylocarpa",
    "ho_thuc_vat": "Fabaceae (họ đậu)",
    "nguon_goc_xuat_su": "Trung Quốc, Mianma, Thái Lan, Lào,Capuchia,… Ở Việt Nam",
    "phan_bo_o_viet_nam": "Từ Bắc vào Nam",
    "dac_diem_hinh_thai": "Cây gỗ lớn, vỏ màu xám trắng, sần sùi nhiều. Phân cành thấp. Lá kép lông chim chẵn, phiến lá chét hình trái xoan, đầu có mũi lồi tù, đuôi gần tròn. Hoa tự hình chùm, hoa lưỡng tính, tràng hoa màu trắng, có 1 cánh, hình tròn có móng dài. Quả đậu hình bao kính. Vỏ quả khi chín hoá gỗ màu đen. Hạt hình trụ có cạnh, vỏ hạt cứng màu đen, dây rốn cứng màu vàng nhạt.",
    "toc_do_sinh_truong": "Chậm",
    "phu_hop_voi": "Cây ưa sáng, thích hợp trên đất bằng phẳng, thành phần cơ giới trung bình, tầng đất sâu.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 35,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:50.273",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Gõ Sưa",
    "slug": "cay-go-sua-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_go_sua.jpg",
    "ten_pho_thong": "Cây Gõ Sưa",
    "ten_khoa_hoc": "Dalbergia tonkinensis",
    "ho_thuc_vat": "Dalbergia tonkinensis Prain",
    "nguon_goc_xuat_su": "Phân bố ở đai độ cao tuyệt đối dưới 500m. Trong tự nhiên tìm thấy trong rừng mưa nhiệt đới và rừng mưa nhiệt đới gió mùa. Chủ yếu phân bổ ở Việt Nam và được tìm thấy rải rác tại Hải Nam, Trung Quốc (tại đây gọi nó là 越南黄檀 - Hoàng (huỳnh) đàn Việt Nam)",
    "phan_bo_o_viet_nam": "Miền Bắc",
    "dac_diem_hinh_thai": "Là cây gỗ nhỡ, rụng lá theo mùa, cao từ 6-12m (cũng có thể cao tới 15m), sinh trưởng trung bình. Thân cây dạng hợp trục, dáng phân tán. Vỏ thân cây màu vàng nâu hay xám, nứt dọc. Cành non màu xanh, có lông mịn thưa. Lá mọc cách, cấu tạo lá dạng kép lông chim lẻ, mỗi là kép có từ 9-17 lá chét đính so-le trên cuống chính. Lá chét hình xoan thuôn, đầu nhọn hoặc có mũi ngọn, đuôi tròn, mặt dưới phiến lá thường có màu tái trắng. Kích thước lá chét dài từ 6–9 cm, rộng từ 3–5 cm, lá ché đính ở đầu cuống kép thường có kích thước lớn hơn các lá còn lại. Cuống chính và các cuống lá chét không lông, phiên lá chét không lông. Có lá kèm nhỏ không lông, sớm rụng.\nHoa mọc ra từ nách lá, thường xuất hiện trước khi lá mọc đầy đủ. Hoa tự tán gồm nhiều bông màu trắng, có kích thước 7-9mm, mùi thơm nhẹ. Mùa hoa vào tháng 2-3. Quả dạng đậu hình trứng thuôn dài, dài 5–7,5 cm, rộng khoảng 2-2,5 cm. Quả chứa 1-2 hạt, mỗi hạt có đường kính khoảng 8-9mm, hình thận dẹp. Quả khi chín không tự nứt.",
    "toc_do_sinh_truong": "Chậm",
    "phu_hop_voi": "Là cây ưa sáng, ưa đất sâu, dày, độ ẩm cao. Phân bố ở đai độ cao tuyệt đối dưới 500m.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 36,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:50.337",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Hoàng Yến",
    "slug": "cay-hoang-yen-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_hoang_yen.jpg",
    "ten_pho_thong": "Cây Hoàng Yến",
    "ten_khoa_hoc": "Tecoma stans",
    "ho_thuc_vat": "Bignoniaceae (Núc nác)",
    "nguon_goc_xuat_su": "Nam Mỹ",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Thân:  thân gỗ nhỏ, thân có nhiều cành nhánh\nLá: dạng lá kép lông chim, mọc đối nhau\nHoa: Cụm hoa màu vàng giống hình chuông mọc ở đầu cành, rũ xuống trông rất đẹp mắt. Cây ra hoa vào tháng 3 đến tháng 5. Sắc hoa vàng sáng rực rỡ, mỗi khi ra hoa, cây thường rụng hết lá để phơi bày cả một vòm tán màu vàng hấp dẫn đầy ấn tượng.\nQuả: quả nang dẹt dài từ 5-7cm, lúc non quả có màu xanh, khi già thì chuyển sang màu nâu xám.",
    "toc_do_sinh_truong": "Nhanh",
    "phu_hop_voi": "Cây huỳnh liên hoa vàng (hoàng yến) là loài cây sống ngoài trời, có thể chịu bóng, ưa nơi thông thoáng và ấm áp. Cây có sức sống tốt, khỏe khoắn nên bạn rất dễ dàng chăm sóc.\nTốc độ sinh trưởng: tốc độ sinh trưởng nhanh\nPhù hợp với: là loài cây ưa nắng, khí hậu nóng ẩm, nên rất phù hợp với điều kiện tự nhiên, khí hậu nước ta.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 37,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:50.403",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Lá Lụa",
    "slug": "cay-la-lua-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_la_lua.jpg",
    "ten_pho_thong": "Cây Lá Lụa",
    "ten_khoa_hoc": "Cynometra ramiflora Linn",
    "ho_thuc_vat": "Caesalpiniaceae (Vang)",
    "nguon_goc_xuat_su": "Châu Á",
    "phan_bo_o_viet_nam": "thường gặp trong các rừng ngập mặn, dựa rạch nước lợ.",
    "dac_diem_hinh_thai": "Thân: Cây thân gỗ cao tới 15-30m, với lá thường rũ xuống. Cây gỗ màu nâu đỏ, chỉ dùng làm củi đun.\nLá: Lá kép chẵn, gồm 2 cặp lá chét màu trắng rồi hồng, xanh, mềm, hình trái xoan ngược hay thon hoặc hơi hình lưỡi liềm; cặp ở trên dài 5-10 (20) cm, rộng 2-4,5 (7,5) cm, không cân xứng ở gốc, nhọn hoặc lõm tròm ở đầu.\nHoa: Cụm hoa gồm 1-2 chùm ngắn ở nách lá, số lượng hoa không nhiều, màu trắng rồi nâu. Ra hoa tháng 6-8.\nQuả: Quả hoá gỗ, dài 2-3cm, có lông hoặc nhẵn, bề mặt xù xì, màu nâu, chứa 2-3 hạt. Có quả tháng 9-10 tới tháng 1-5.",
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": "Thường gặp trong các rừng ngập mặn, dựa rạch nước lợ.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 38,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:50.467",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Mù U",
    "slug": "cay-mu-u-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_mu_u.jpg",
    "ten_pho_thong": "Cây Mù U",
    "ten_khoa_hoc": "Calophyllum inophyllum",
    "ho_thuc_vat": "Calophyllaceae (Cồng)",
    "nguon_goc_xuat_su": "Đông Phi, Nam Ấn Độ, Malesia, Úc",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Đây là cây cành thấp, lớn chậm với tán rộng. Chiều cao từ 8–20 m. Lá cứng, gân phụ rất nhiều và song song. Hoa trắng to, rộng 25mm. Hoa nở quanh năm nhưng thường nở vào hai mùa riêng biệt cuối mùa Xuân và cuối mùa Thu. Quả có nhân cứng màu xanh, rất tròn, có đường kính 2–3 cm và có một hạt. Quả khi chín chuyển sang màu vàng hoặc đỏ nâu. Hạt có chứa một chất dầu, màu vàng lục, mùi riêng biệt gọi là dầu mù u.",
    "toc_do_sinh_truong": "Trung bình",
    "phu_hop_voi": "Cây này thường được trồng ở các vùng ven biển và ở các khu rừng đất thấp. Tuy nhiên vẫn có thể trồng nó ở những khu đất trong đất liền có độ cao vừa phải. Nó có khả năng chịu được nhiều loại đất khác nhau như đất cát ven biển, đất sét hay đất bạc màu.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 39,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:50.53",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Sầu Đâu",
    "slug": "cay-sau-dau-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_sau_dau.jpg",
    "ten_pho_thong": "Cây Sầu Đâu",
    "ten_khoa_hoc": "Azadirachta indica",
    "ho_thuc_vat": "Meliaceae",
    "nguon_goc_xuat_su": "Bangladesh, Ấn Độ, Myanma, và Pakistan",
    "phan_bo_o_viet_nam": "Rộng khắp",
    "dac_diem_hinh_thai": "Cây cao 15–20 m, hiếm khi cao 35–40 m. Đây là cây thường xanh nhưng gặp khi hạn hán thì cây có thể rụng hết lá. Nhánh cây tỏa rộng có tán rậm hơi tròn hoặc ô van và có thể đạt đường kính 15–20 m. Hoa nhỏ, mọc thành từng chùm, màu tím, quả hình bầu dục, to khoảng bằng đầu ngón tay.",
    "toc_do_sinh_truong": "Nhanh",
    "phu_hop_voi": "Phát triển trong mùa khô nhiệt đới hay cận nhiệt đới, bởi vì sầu đâu hệ rễ rất sâu, có thể chịu được lạnh nhưng không chịu được nhiệt độ lạnh kéo dài.",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 40,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:50.593",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Trâm Bầu",
    "slug": "cay-tram-bau-1",
    "id_danh_muc": 12,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_tram_bau.jpg",
    "ten_pho_thong": "Cây Trâm Bầu",
    "ten_khoa_hoc": "Combretum quadrangulareKurz",
    "ho_thuc_vat": "Combretaceae",
    "nguon_goc_xuat_su": "cây mọc hoang ở khắp các tỉnh phía nam, nhất là vùng đồng bằng",
    "phan_bo_o_viet_nam": "Ven các con kênh vùng đồng bằng sông Cửu Long",
    "dac_diem_hinh_thai": "Trâm bầu là dạng cây bụi hoặc gỗ nhỏ, cao từ 2-10 m, có khi tới 12 m. Thân trâm bầu có nhiều cành ngắn, khi rụng lá trông như gai. Cành non có 4 cạnh, lá mọc đối, hình trứng dài, chóp tù hay nhọn. Hai mặt lá đều có lông, mặt dưới nhiều hơn. Chiều dài của lá là 3-7,5 cm, chiều rộng 1,5-4 cm.",
    "toc_do_sinh_truong": "Trung Bình",
    "phu_hop_voi": "",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 41,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:50.657",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },
  {
    "ten_cay": "Cây Trâm Vỏ Đỏ",
    "slug": "cay-tram-vo-do-1",
    "id_danh_muc": 11,
    "id_phan_loai": 25,
    "id_chung_loai": 5,
    "id_pr_cay": 5,
    "hinh_anh_dai_dien": "/UploadFile/trees\\Cay_tram_vo_do.jpg",
    "ten_pho_thong": "Cây Trâm Vỏ Đỏ",
    "ten_khoa_hoc": "Syzygium zeylanicum (L.)",
    "ho_thuc_vat": "Myrtaceae (Sim).",
    "nguon_goc_xuat_su": "Nam Ấn Độ, Malaixia tới Inđônêxia",
    "phan_bo_o_viet_nam": "Chỉ gặp ở các tỉnh phía Nam nước ta, trong các quần hệ thứ sinh ở vĩ độ thấp dưới 1000m từ KonTum vào Nam.",
    "dac_diem_hinh_thai": "Cụm hoa gồm một hoa mọc ở kẽ lá và nhiều hoa nhỏ ở đầu cành, màu vàng nhạt. Quả dài  từ 18-20 mm, rộng 7-8 mm, có 4 cành mỏng chứa 1 hạt hình thoi, rộng 4 mm, có rìa. Các bộ phận dùng làm thuốc là hạt, rễ, lá và vỏ.",
    "toc_do_sinh_truong": "",
    "phu_hop_voi": "",
    "chi_tiet_khac": "0",
    "ghi_chu": "",
    "mo_ta": null,
    "id": 42,
    "trang_thai": "true",
    "ngay_tao": "2019-02-16T10:49:50.72",
    "nguoi_tao": "administrator",
    "ngay_cap_nhat": null,
    "nguoi_cap_nhat": null
  },]
    